// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjuqaehsjhfjnzzcwgli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqdXFhZWhzamhmam56emN3Z2xpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MjM4OTAsImV4cCI6MjA2MTk5OTg5MH0.ZeZ87k7YgsS-KNL1wjARvxRN1ofUTA8hvQidDjPs8w4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});